"""add speaker_name to event

Revision ID: ea6156e079b7
Revises: 1b7730d6da34
Create Date: 2026-02-26 06:18:28.235498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6156e079b7'
down_revision: Union[str, Sequence[str], None] = '1b7730d6da34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('speaker_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'speaker_name')
    # ### end Alembic commands ###
